install.packages("dplyr")
library(dplyr)
# sessionInfo()
 sessionInfo()
## Inbuilt data set called "mtcars"
mtcars
mtcars %>% head()
dim()
mtcars %>% dim()
mtcars %>% nrow()
mtcars %>% ncol()
mtcars %>% names()
mtcars %>% class()
mtcars %>% summary()
iris %>% summary()
iris %>% glimpse()
iris2 <- iris %>% filter()
filter(iris, Species == "Setosa")
iris2 <- iris %>% filter( Species == "Setosa")
iris2 %>% dim()
iris3 <- iris %>% filter(Sepal.length > 2))
iris3 <- iris %>% filter(Sepal.Length > 2))
iris3 <- iris %>% filter(Sepal.Length > 2)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 3)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5.2)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5.4)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5.6)
iris3 %>% dim()
iris %>% group_by(Species) %>% summarize(mean(Sepal.Length))
iris %>% group_by(Species) %>% summarize(var(Sepal.Length))
iris %>% group_by(Species) %>% summarize(sd(Sepal.Length))
iris3 %>% dim()
mtcars %>% group_by(cyl) %>% summarize(mean(mpg))
help(mtcars)
mtcars %>% select(1:4)
mtcars %>% s3elect(1:drat)
mtcars %>% s3elect(cyl:drat)
mtcars %>% select(2:4, everything())
mtcars %>% mutate(sqrtMPG= sqrt(qsec))
mtcars %>% mutate(sqrtQSEC= sqrt(qsec))
mtcars %>% mutate(sqrtMPG= sqrt(mpg), logMPG=log(mpg)%>% 
select(mpg, sqrtMPG, logMPG, everything()))
